#!/usr/bin/python3

import sqlite3
import os

DB_PATH_OLD = "betanin.db"
DB_PATH_NEW = os.path.expanduser("~/.local/share/betanin/betanin.db")

conn_old = sqlite3.connect(DB_PATH_OLD)
curs_old = conn_old.cursor()
conn_new = sqlite3.connect(DB_PATH_NEW)
curs_new = conn_new.cursor()

old_t_ids = {}

# torrents
results = conn_old.execute("SELECT * FROM torrents")
for result in results.fetchall():
    curs_new.execute(
        'insert into "torrents" ("name", "path", "status", "created", "updated") values (?, ?, ?, ?, ?)',
        result[1:],
    )
    old_t_ids[result[0]] = curs_new.lastrowid
conn_new.commit()
print(f"{len(old_t_ids)} torrents found")

# lines
results = conn_old.execute("SELECT * FROM lines")
for result in results.fetchall():
    try:
        old_id = old_t_ids[int(result[-1])]
    except KeyError:
        continue
    curs_new.execute(
        'insert into "lines" ("index", "data", "torrent_id") values (?, ?, ?)',
        result[1:-1] + (old_id,),
    )
conn_new.commit()
