#!/usr/bin/env python3

# 3rd party
from flask import Flask

# betanin
from betanin.config import Config
from betanin.extensions import db
from betanin.api.orm.models.torrent import Line
from betanin.api.orm.models.torrent import Torrent


# create and configure app
app = Flask('throwaway')
app.config.from_object(Config)

# make db
with app.app_context():
    db.init_app(app)
    db.create_all()
