#!/usr/bin/env python3

from flask import Flask

from betanin.api.orm.models.torrent import Line
from betanin.api.orm.models.remote import Remote
from betanin.api.orm.models.torrent import Torrent
from betanin.extensions import db
from betanin.config import Config

# create and configure app
app = Flask('throwaway')
app.config.from_object(Config)

# make db
with app.app_context():
    db.init_app(app)
    db.create_all()
