FROM python:3.6.6-alpine3.6
LABEL maintainer="Senan Kelly <senan@senan.xyz>"
COPY ./requirements-docker.txt /
RUN \
    apk add --no-cache libev build-base && \
    pip --no-cache-dir install -U \
        https://github.com/caronc/apprise/archive/master.zip \
        -r /requirements-docker.txt
WORKDIR /src
COPY . .
RUN pip install -U -e .
VOLUME [ \
    "/root/.local/share/betanin/" \
    "/root/.config/betanin/" \
    "/root/.config/beets/" \
]
ENV \
    PYTHONUNBUFFERED=1 \
    PYTHONWARNINGS="ignore:Unverified HTTPS request"
CMD [ "betanin" ]
