FROM sentriz/betanin
# or build the image with `docker build . -t betanin-dev`
# and then use `FROM betanin-dev` here
COPY root/ /
COPY . .
RUN pip --no-cache-dir install -U -e .
RUN cd /src/betanin_client && npm run-script build