#!/usr/bin/bash

echo 1
sleep 0.4
echo 2
sleep 0.4
echo 3
sleep 1.4
echo 1
sleep 0.4
echo 2
sleep 0.4
echo 3
sleep 1.4
read -p 'give me a howdy: ' howdy
echo "your howdy was: $howdy"
sleep 1.4
echo 1
sleep 0.4
echo 2
sleep 0.4
echo 3
sleep 1.4
echo 1
sleep 0.4
echo 2
sleep 0.4
echo 3
sleep 1.4
echo 1
sleep 0.4
echo 2
sleep 0.4
echo 3
sleep 1.4
echo 'goodbye'
