#!/usr/bin/env python3

import click
import subprocess
import os


_cwd = os.getcwd()
CLIENT_DIR = os.path.join(_cwd, 'app', 'client', 'vue_app')


@click.group()
def cli():
    pass


def _bash(cmd, **kwargs):
    click.echo('>>> {}'.format(cmd))
    return subprocess.call(cmd, env=os.environ, shell=True, **kwargs)


@cli.command(help='serve api dev server',
             name='serving-dev-api')
def serve_dev_api():
    from app import app
    app.run(
        host='localhost', 
        port=5000,
        use_reloader=False,
    )


@cli.command(help='serve client dev server',
             name='serving-dev-client')
def serve_dev_client():
    _bash('npm run serve',
          cwd=CLIENT_DIR)


@cli.command(help='serve mock transmission',
             name='serving-mock-transmission')
@click.option('--percent', default=1)
@click.option('--period', default=1)
def serve_dev_client(**kwargs):
    from mock_transmission_server import app
    from mock_transmission_server import start_inc_worker
    start_inc_worker(**kwargs)
    app.run(
        host='localhost', 
        port=5001,
        use_reloader=False,
    )


@cli.command(help='build client',
             name='building-client')
def build_client():
    _bash('npm run build',
          cwd=CLIENT_DIR)


if __name__ == '__main__':
    cli()
