#!/usr/bin/env python3

# python
# standart library
import code

# 3rd party
from flask import Flask

# betanin
from betanin.config import Config
from betanin.extensions import db
from betanin.api.orm.models.torrent import Line
from betanin.api.orm.models.torrent import Torrent


# create and configure app
app = Flask('throwaway')
app.config.from_object(Config)

# start repl
with app.app_context():
    db.init_app(app)
    console = code.InteractiveConsole(locals=globals())
    console.interact(banner=f'''welcome to the betanin shell.
available globals include `Torrent`, `Line`, and `db`,
use `exit()` to exit.''')
