#!/bin/sh

export PYTHONWARNINGS='ignore:Unverified HTTPS request'
export FLASK_APP='utilities.mock_transmission_server:create_app()'
export MOCK_TRANS_AMOUNT='5'
export MOCK_TRANS_PERIOD='1'

# can't seen to set port number from env var (FLASK_RUN_PORT not working)
if [ "$1" = "run" ]; then
    extra_args="--port 5001"
fi

flask $@ $extra_args
