"""empty message

Revision ID: f7638c143743
Revises: 8a50d0ea6216
Create Date: 2019-03-07 11:44:37.428235

"""
# 3rd party
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "f7638c143743"
down_revision = "8a50d0ea6216"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lines")
    op.drop_table("torrents")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "torrents",
        sa.Column("id", sa.VARCHAR(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=True),
        sa.Column("path", sa.VARCHAR(), nullable=True),
        sa.Column("status", sa.VARCHAR(length=11), nullable=True),
        sa.Column("created", sa.DATETIME(), nullable=True),
        sa.Column("weed", sa.VARCHAR(), nullable=True),
        sa.Column("updated", sa.DATETIME(), nullable=True),
        sa.CheckConstraint(
            "status IN ('COMPLETED', 'ENQUEUED', 'FAILED', 'IGNORED', 'NEEDS_INPUT', 'PROCESSING')",
            name="status",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lines",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("index", sa.INTEGER(), nullable=True),
        sa.Column("data", sa.VARCHAR(), nullable=True),
        sa.Column("torrent_id", sa.VARCHAR(), nullable=True),
        sa.ForeignKeyConstraint(["torrent_id"], ["torrents.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
