"""empty message

Revision ID: 7ab0dc3fbc15
Revises: 9c5e830ec21b
Create Date: 2018-10-15 17:39:45.951857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ab0dc3fbc15'
down_revision = '9c5e830ec21b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.create_foreign_key(None, 'torrents', 'remotes', ['remote_id'], ['id'])
    op.drop_column('torrents', 'remote_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('torrents', sa.Column('remote_type', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'torrents', type_='foreignkey')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', sa.FLOAT(), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
