"""empty message

Revision ID: 9cb8f6783bf5
Revises: 
Create Date: 2018-10-02 18:55:10.814762

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_json


# revision identifiers, used by Alembic.
revision = '9cb8f6783bf5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('config', sqlalchemy_json.NestedMutableJson(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('torrents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('remote_status', sa.Enum('COMPLETED', 'DOWNLOADING', 'INACTIVE', 'UNKNOWN', name='remotestatus'), nullable=True),
    sa.Column('beta_status', sa.Enum('COMPLETED', 'ENQUEUED', 'FAILED', 'IGNORED', 'NEEDS_INPUT', 'PROCESSING', 'UNKNOWN', 'WAITING', name='betastatus'), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('should_process', sa.Boolean(), nullable=True),
    sa.Column('tooltip', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('torrent_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['torrent_id'], ['torrents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lines')
    op.drop_table('torrents')
    op.drop_table('remotes')
    # ### end Alembic commands ###
