#!/bin/bash 

if [[ -z "$SOURCE_COMMIT" ]]; then
    SOURCE_COMMIT="$(git rev-parse --short HEAD)"
    echo "SOURCE_COMMIT was not set. setting to $SOURCE_COMMIT"
fi

docker build \
    -t "$IMAGE_NAME" \
    --build-arg "SOURCE_COMMIT=$SOURCE_COMMIT" \
    --build-arg "DOCKER_TAG=$DOCKER_TAG" \
    .
