#!/bin/sh

echo one
echo two
echo three
echo four
echo five
echo six
echo seven
echo eight
echo nine
echo ten
echo eleven
echo twelve
echo thirteen
echo fourteen
echo fifteen
echo sixteen
echo seventeen
echo eighteen
echo nineteen
echo twenty
echo twenty-one
echo twenty-two
# read eggs
# echo $eggs $eggs
echo twenty-four
echo twenty-five
echo twenty-six
echo twenty-seven
echo twenty-eight
echo twenty-nine
echo thirty
